name: Docker build and push
 
on:
  push:
    branches:
    - main 
  schedule:
    - cron:  '0 0 * * 2'

jobs:
  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [
          { java: '8', node: '12', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '8', node: '12', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '8', node: '12', ubuntu: 'focal' , arch: 'linux/amd64'},
          # { java: '11', node: '12', ubuntu: 'xenial', arch: 'linux/amd64,linux/arm64' },
          # { java: '11', node: '12', ubuntu: 'bionic', arch: 'linux/amd64,linux/arm64' },
          # { java: '11', node: '12', ubuntu: 'focal', arch: 'linux/amd64,linux/arm64' },
          { java: '11', node: '12', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '11', node: '12', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '11', node: '12', ubuntu: 'focal', arch: 'linux/amd64' },
          { java: '16', node: '12', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '16', node: '12', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '16', node: '12', ubuntu: 'focal', arch: 'linux/amd64' },
          { java: '8', node: '14', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '8', node: '14', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '8', node: '14', ubuntu: 'focal', arch: 'linux/amd64' },
          # { java: '11', node: '14', ubuntu: 'xenial', arch: 'linux/amd64,linux/arm64' },
          # { java: '11', node: '14', ubuntu: 'bionic', arch: 'linux/amd64,linux/arm64' },
          # { java: '11', node: '14', ubuntu: 'focal', arch: 'linux/amd64,linux/arm64' },
          { java: '11', node: '14', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '11', node: '14', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '11', node: '14', ubuntu: 'focal', arch: 'linux/amd64' },
          { java: '16', node: '14', ubuntu: 'xenial', arch: 'linux/amd64' },
          { java: '16', node: '14', ubuntu: 'bionic', arch: 'linux/amd64' },
          { java: '16', node: '14', ubuntu: 'focal', arch: 'linux/amd64' }
        ]
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: poad
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate image name
      env:
        ARCH: ${{ matrix.versions.arch }}
        JAVA: ${{ matrix.versions.java }}
        NODE: ${{ matrix.versions.node }}
        UBUNTU: ${{ matrix.versions.ubuntu }}
      run: echo "IMAGRE_NAME=poad/aws-cdk-docker:node${NODE}-jdk${JAVA}-${UBUNTU}" >> $GITHUB_ENV

    - name: "Build image and push"
      env:
        IMAGRE_NAME: ${{ env.IMAGRE_NAME }}
        ARCH: ${{ matrix.versions.arch }}
        JAVA: ${{ matrix.versions.java }}
        NODE: ${{ matrix.versions.node }}
        UBUNTU: ${{ matrix.versions.ubuntu }}
      run: docker buildx build --platform "${ARCH}" --build-arg JAVA_VERSION="${JAVA}" --build-arg NODE_VERSION="${NODE}" --build-arg UBUNTU_VERSION="${UBUNTU}" -t "${IMAGRE_NAME}" --push .
