name: Docker build
 
on:
  push:
    branches:
    - master 

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11]
        node: [10, 12, 14]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build and push image
        run: |
          echo "::set-env name=DOCKER_USERNAME::${{ secrets.DOCKER_USERNAME }}"
          bash -x docker_push.sh ${{ matrix.jdk }} ${{ matrix.node }} && bash -x docker_push.sh ${{ matrix.jdk }} ${{ matrix.node }} ${{ secrets.DOCKER_PASSWORD }}
