name: Docker build and push
 
on:
  push:
    branches:
    - master 
  schedule:
    - cron:  '0 0 * * 0'  

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [8, 11]
        node: [10, 12, 14]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set environment variables
        run: echo "::set-env name=DOCKER_USERNAME::${{ secrets.DOCKER_USERNAME }}"
      - name: Build image
        run: docker build --rm --build-arg JAVA_VERSION=${{ matrix.jdk }} --build-arg NODE_VERSION=${{ matrix.node }} -t ${{ secrets.DOCKER_USERNAME }}/aws-cdk-docker:node-${{ matrix.node }}-jdk${{ matrix.jdk }} .
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aws-cdk-docker:node-${{ matrix.node }}-jdk${{ matrix.jdk }}
